### ISSUE TITLE
Account registration

### ISSUE THREAD

**Issue by jerzabek** [jerzabek/pinehaus#8]
Users should be able to register new accounts on the Pinehaus application. This requires both backend and frontend infrastructure.

## 💻 Backend 

- Account entity with appropriate fields
- API for registering new account
- Ability to sign up with google. **We won't bother with emails/passwords.**
- Some sort of middleware to protect certain routes - make them available only to authenticated users

## 🌐 Frontend 
- Signup page with "Sign up with google" button
- Component for authenticated routes
- Global context to make user account details available throughout the application

**Comment by fesimaxu** [comment]
hey, I am interested in working on this project

**Comment by fesimaxu** [comment]
I will be implementing the registration API using 
node js
authentication with Jsonwebtoken
authorization to allow users to login before they can access some
